language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script: composer install -n

script: vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml

after_script: php vendor/bin/coveralls -v
