parameters:
    glooby_task.queue_processor.limit: 10

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Glooby\TaskBundle\Task\PingTask: '@glooby_task.ping'
    Glooby\TaskBundle\Schedule\ScheduleRegistry: '@glooby_task.schedule_registry'
    Glooby\TaskBundle\Synchronizer\ScheduleSynchronizer: '@glooby_task.schedule_synchronizer'
    Glooby\TaskBundle\Manager\TaskManager: '@glooby_task.task_manager'
    Glooby\TaskBundle\Task\TaskRunner: '@glooby_task.task_runner'
    Glooby\TaskBundle\Queue\QueuePruner: '@glooby_task.queue_pruner'
    Glooby\TaskBundle\Queue\QueueScheduler: '@glooby_task.queue_scheduler'
    Glooby\TaskBundle\Queue\QueueProcessor: '@glooby_task.queue_processor'
    Glooby\TaskBundle\Queue\QueueMonitor: '@glooby_task.queue_monitor'

    glooby_task.ping:
        class: Glooby\TaskBundle\Task\PingTask
        tags:
            - { name: glooby.scheduled_task }

    glooby_task.schedule_registry:
        class: Glooby\TaskBundle\Schedule\ScheduleRegistry
        calls:
            - [setReader,    ['@annotations.reader']]
            - [setContainer, ['@service_container']]

    glooby_task.schedule_synchronizer:
        class: Glooby\TaskBundle\Synchronizer\ScheduleSynchronizer
        calls:
            - [setDoctrine,         ['@doctrine']]
            - [setScheduleRegistry, ['@glooby_task.schedule_registry']]

    glooby_task.task_manager:
        class: Glooby\TaskBundle\Manager\TaskManager
        calls:
            - [setDoctrine,         ['@doctrine']]

    glooby_task.task_runner:
        class: Glooby\TaskBundle\Task\TaskRunner
        calls:
            - [setLogger,       ['@logger']]
            - [setContainer,    ['@service_container']]
            - [setTaskManager,  ['@glooby_task.task_manager']]

    glooby_task.queue_pruner:
        class: Glooby\TaskBundle\Queue\QueuePruner
        calls:
            - [setDoctrine,         ['@doctrine']]
        tags:
            - { name: glooby.scheduled_task }

    glooby_task.queue_scheduler:
        class: Glooby\TaskBundle\Queue\QueueScheduler
        calls:
            - [setDoctrine,    ['@doctrine']]
            - [setTaskManager, ['@glooby_task.task_manager']]

    glooby_task.queue_processor:
        class: Glooby\TaskBundle\Queue\QueueProcessor
        calls:
            - [setDoctrine,     ['@doctrine']]
            - [setLimit,        ['%glooby_task.queue_processor.limit%']]
            - [setDebug,        ['%kernel.debug%']]

    glooby_task.queue_monitor:
        class: Glooby\TaskBundle\Queue\QueueMonitor
        calls:
            - [setDoctrine,     ['@doctrine']]
            - [setTaskManager,  ['@glooby_task.task_manager']]

    glooby_task.task_run_command:
        class:
            Glooby\TaskBundle\Command\Task\RunCommand
        tags:
            - { name: 'console.command', command: 'task:run' }

    glooby_task.scheduler_run_command:
        class:
            Glooby\TaskBundle\Command\Scheduler\RunCommand
        tags:
            - { name: 'console.command', command: 'scheduler:run' }

    glooby_task.scheduler_prune_command:
        class:
            Glooby\TaskBundle\Command\Scheduler\PruneCommand
        tags:
            - { name: 'console.command', command: 'scheduler:prune' }

    glooby_task.scheduler_sync_command:
        class:
            Glooby\TaskBundle\Command\Scheduler\SyncCommand
        tags:
            - { name: 'console.command', command: 'scheduler:sync' }
